### ISSUE TITLE
npm start fail

### ISSUE THREAD

**Issue by gaozhidf** [elastic/kibana-plugin-helpers#44]
```
 ERROR  Extra serve options "--dev" must have a value

undefined
```

And option "--dev" has been removed, from https://github.com/elastic/kibana/issues/8394
but i still meet the problem when i use plugin-helpers from template-kibana-plugin.

the version of kibana,
```
kibana: 5.5.0
```

the version of template-kibana-plugin
```
  "devDependencies": {
    "@elastic/eslint-config-kibana": "^0.6.1",
    "@elastic/plugin-helpers": "^7.0.0",
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-plugin-babel": "^4.1.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-mocha": "^4.9.0",
    "eslint-plugin-react": "^7.0.1",
    "expect.js": "^0.3.1"
  }
```

**Comment by w33ble** [comment]
The issue you linked to is rightly closed, we don't ship the dev server with the production build. You need to run against the repo, as [outlined in CONTRIBUTING.MD](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment).

Are you saying you got that error with the repo?

**Comment by gaozhidf** [comment]
yes, i miss that, thx

**Comment by anitaIncaendo** [comment]
@gaozhidf what did you miss? please specify it. because i'm also stuck in same kind of issue, when trying to run npm start

**Comment by w33ble** [comment]
In their case, they were trying to develop a plugin using the version of Kibana downloaded from https://www.elastic.co/downloads/kibana. That doesn't work, you have to clone the Kibana repo at https://github.com/elastic/kibana and use that.

See [the CONTRIBUTING.md info](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#setting-up-your-development-environment) for instructions on setting up your development environment. You need to do this in order to develop a plugin too.
