### ISSUE TITLE
The package task does not observe the buildDestination option

### ISSUE THREAD

**Issue by nrgiroux** [elastic/kibana-plugin-helpers#51]
In a 'Cmder' environment under 'Win10', I have no .zip file produced.
The plugin is well done/functional under the right path.
No need to mention that the command is launched **without** the '--skip-archive' option.

**Comment by w33ble** [comment]
Do you get any kind of output, like an error or something, or do things just kind of silently fail?

Do you have the un-packaged/un-compressed version of the plugin in the `build` path?

**Comment by w33ble** [comment]
Oh, and also, what version of `@elastic/plugin-helpers` do you have in your local `package.json` file?

**Comment by nrgiroux** [comment]
Hi,

I have no erroneous output.
Yes the plugin is produced at the build path (and functional when copied to
Kibana/plugins).

λ cat kibana-plugin-helpers\package.json
{
  "name": "@elastic/plugin-helpers",
  "version": "7.1.1",

Also:

λ npm ls gulp-zip
@elastic/plugin-helpers@7.1.1 X:\SirenS\compbio\kibana-plugin-helpers
`-- gulp-zip@3.1.0

2017-11-07 12:22 GMT-05:00 Joe Fleming <notifications@github.com>:

**Comment by w33ble** [comment]
Thanks. One last thing; do you have any `.kibana-plugin-helpers.*` files in the root of your plugin? I know you said you aren't using the `--skip-archive` flag, but I want to confirm that you don't have `skipArchive` in one a a helpers config file too.

**Comment by nrgiroux** [comment]
Nothing on this side; it's a 'in house' plugin so it doesn't have 'hidden'
files.

Maybe the  '--skip-archive' option could take an explicit boolean; just a
thought...

2017-11-07 14:55 GMT-05:00 Joe Fleming <notifications@github.com>:

**Comment by nrgiroux** [comment]
Hi,

I just succeeded in obtaining a .zip !
The destination dir (-d) has to be 'build'. Did I miss something in the
docs ?
If I define the destination dir as '-d another-name', no .zip is produced.

2017-11-08 8:57 GMT-05:00 Richard Giroux <nrgiroux@gmail.com>:

**Comment by w33ble** [comment]
Oh, I didn't realize you were using that flag. Maybe there's a bug with that, I'll investigate. Thanks for following up!

EDIT: Yup, the package output, which is what creates the zip file, is hard-coded to use `build`. See https://github.com/elastic/kibana-plugin-helpers/blob/master/tasks/build/create_package.js#L9

Thanks again 👍

**Comment by nrgiroux** [comment]
Tanks,

I should have sent my whole command line at first.

2017-11-08 12:53 GMT-05:00 Joe Fleming <notifications@github.com>:

**Comment by w33ble** [comment]
It's cool, I should have asked ;)

I'll hopefully get that fixed later today. Thanks again for reporting it and following up with details.

**Comment by w33ble** [comment]
It's cool, I should have asked ;)

I'll hopefully get that fixed later today. Thanks again for reporting it and following up with details.

**Comment by nrgiroux** [comment]
Maybe out of this bug's scope, but while you're at it: why does the zip file have a kibana/ path prefix in it ?
I think users would like to 'unzip my-plugin.zip -d kibana/plugins/{my-plugin not kibana/my-plugin}'.

Thanks

**Comment by w33ble** [comment]
The `kibana` path is intentional for the plugin to work with Kibana's tooling. It's actually the way all Elastic product plugins work, so that you can package up plugins for multiple products in a single zip file. For example, your zip file can include plugins for Elasticsearch and Beats, and their structure is the same, `elasticsearch/your-plugin-name` and `beats/your-plugin-name`. This is how we distribute [X-Pack](https://www.elastic.co/products/x-pack), one file that you install in both Elasticsearch and Kibana.

You aren't actually supposed to unzip Kibana plugins by hand like that, you're *supposed* to use the plugin installer via `./bin/kibana-plugin install`. That tool will take care of the path for you, installing the plugin into the `kibana/plugins` path automatically.

The the `kibana` path is not a bug, it's a feature. All that said, I can understand why you might not want to use the built in installer, and in fact I wrote an [alternative tool to make plugin installation a little easier](https://github.com/w33ble/kbn-shoehorn).

**Comment by nrgiroux** [comment]
Thank you very much for the info.

I don't want to nag, but the current (5.6) Kibana doc still says:

> You can also install a plugin manually by moving the plugin file to the plugins directory and unpacking the plugin files into a new directory.

What was unclear to me in the kibana-plugin install process (and doc) was using a local file source with file:///full_path/to/plugin.zip. This works like a charm thanks to your kibana-plugin-helper !

Thanks again.

**Comment by w33ble** [comment]
> @elastic/plugin-helpers 7.1.2 published 🎉

Fixed in the new release.
